# 檔案名稱: docker-compose.yml
services:
  mongodb:
    image: mongo:latest
    container_name: week12_mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASS}
      - MONGO_INITDB_DATABASE=week12
    ports:
      - "27017:27017"
    volumes:
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb_data:/data/db

volumes:
  mongodb_data: